version: '3.8'

services:
  db:
    build: ./database
    container_name: mysql-db
    volumes:
      - my-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

  app:
    build: ./server
    container_name: node-server
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - my-network

  client:
    build: ./client     
    container_name: bun-client
    ports:
      - "3000:3000"       
    networks:
      - my-network
    volumes:
      - ./client:/app    

networks:
  my-network:

volumes:
  my-db-data:
